### ISSUE TITLE
Should the docs on `silent` be clarified

### ISSUE THREAD

**Issue by togakangaroo** [malijs/examples#7]
In the [docs](https://mali.js.org/api/#mali-silent-boolean)

> mali.silent : Boolean

> Whether to log errors in onerror. Default: false

I *think* the intention is to say that `true` will suppress the error logging, but if you're just reading the docs it reads as if `false` will not log errors. Maybe change the wording to 

> Whether to suppress error logging in the default `onerror`. Default: `false`

**Comment by bojand** [comment]
Hello, thanks for bringing this to my attention. I agree the documentation wasn't the best. I have clarified it in the documentation as you suggested.
